config/routes.rb
Rails.application.routes.draw do

  resources :open_houses
  resources :names

  devise_for :users
  resources :expenses
 root 'site#index'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
	belongs_to :user
def self.search_for(query)
		validates_presence_of :title, :amount, :transaction_date
		validates :title, length: { minimum: 1}
		def self.search_for(query)
	where('name LIKE :query OR description LIKE :query', query: "%#{query}%")
end
end
	#ensure that user_id is present
	# validates :user_id, presence: true
	#ensure that a title is present and at least 4 characters long
	# validates :title, length: { minimum: 4}, presence:true
	#ensure that an amount is present
#	validates :transaction_date, {minimum: 0} presence:true
	# validates :amount, length: { minimum: 2}, presence:true

end

def self.to_csv(all_expenses)
	attributes = %w{id title amount}
	CSV.generate(options) do |csv|
		csv << attributes
		all.each do |expense|
			 csv << expense.attributes.map{ |attr| expense.send(attr)}

		end
	end 
	def expense
   ActionController::Base.helpers.number_to_currency(self[:expense])
end
end

app/models/open_house.rb
class OpenHouse < ActiveRecord::Base
	belongs_to :user
	def self.search_for(query)
		validates_presence_of :title, :amount
		validates :title, length: { minimum: 1}
		def self.search_for(query)
	where('name LIKE :query OR description LIKE :query', query: "%#{query}%")
end
end
end

app/models/user.rb
class User < ActiveRecord::Base
	include Gravtastic   
  gravtastic 
	has_many :expenses
	has_many :open_houses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	require 'csv'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = current_user.expenses.all
   # respond_to do |format|
    #  format.html
    
    #  format.csv  { send_data @expenses.to_csv }
# headers['Content-Dispositions'] = "attachmnet; filename=\"expense-list\""
# headers['Content-Type'] 
        
 #     format.xls # {send_data @expenses.to_csv(col_sep: "\t")}
      
  #  end
 # end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = current_user.expenses.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = current_user.expenses.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = current_user.expenses.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :amount, :transaction_date)
    end
    
end

app/controllers/open_houses_controller.rb
class OpenHousesController < ApplicationController
  before_action :set_open_house, only: [:show, :edit, :update, :destroy]

  # GET /open_houses
  # GET /open_houses.json
  def index
    @open_houses = current_user.open_houses.all
  end

  # GET /open_houses/1
  # GET /open_houses/1.json
  def show
  end

  # GET /open_houses/new
  def new
    @open_house = current_user.open_houses.new
  end

  # GET /open_houses/1/edit
  def edit
  end

  # POST /open_houses
  # POST /open_houses.json
  def create
    @open_house = current_user.open_houses.new(open_house_params)

    respond_to do |format|
      if @open_house.save
        format.html { redirect_to @open_house, notice: 'Open house was successfully created.' }
        format.json { render :show, status: :created, location: @open_house }
      else
        format.html { render :new }
        format.json { render json: @open_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /open_houses/1
  # PATCH/PUT /open_houses/1.json
  def update
    respond_to do |format|
      if @open_house.update(open_house_params)
        format.html { redirect_to @open_house, notice: 'Open house was successfully updated.' }
        format.json { render :show, status: :ok, location: @open_house }
      else
        format.html { render :edit }
        format.json { render json: @open_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /open_houses/1
  # DELETE /open_houses/1.json
  def destroy
    @open_house.destroy
    respond_to do |format|
      format.html { redirect_to open_houses_url, notice: 'Open house was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_open_house
      @open_house = current_user.open_houses.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def open_house_params
      params.require(:open_house).permit(:Name, :Phone_number, :Email_address, :How_did_you_here_about_our_open_house, :Are_you_working_with_a_Realtor, :Realtors_name_and_contact_information, :Would_you_like_to_be_emailed_new_properties)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/expenses' # Or :prefix_to_your_route
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	
  def index
  	# retrieve all Expenses ordered by descending creation timestamp
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/open_houses_helper.rb
module OpenHousesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/expenses/_form.html.erb
<%= form_for @expense, :html => { :class => "form-horizontal expense" } do |f| %><form role="form" class="form-inline">

  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :transaction_date %><br>
    <%= f.text_field :transaction_date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</form>

app/views/expenses/edit.html.erb
<%- model_class = Expense -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/expenses/index.html.erb
<%- model_class = Expense -%>
<%= form_tag "/" , method: :get do %>
<%= text_field_tag :q, params[:q] %>
<%= submit_tag "Search" %>
<% end%>
<P>
  Download Your Expenses:
  
  <%= link_to "", expenses_path(format: "csv"), class: "btn-primary" %>
  <%= link_to "Excel", expenses_path(format: "xls"), class: "btn-primary" %>
 
  
</p>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:transaction_date) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%  %>
    <% @expenses.each do |expense| %>
    <%  %>
      <tr>
        <td><%= link_to expense.id, expense_path(expense) %></td>
        <td><%= expense.title %></td>
        <td><%= expense.transaction_date %></td>
        <td><%= number_to_currency  expense.amount %></td>
        <td><%= expense.user_id %></td>
        <td><%=l expense.created_at %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_expense_path(expense), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      expense_path(expense),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>
<p  align="left">           Total Expenses &nbsp; <%= number_to_currency current_user.expenses.sum(:amount) %></p>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_expense_path,
            :class => 'btn btn-primary' %>

app/views/expenses/index.xls.erb
<table border="1">
<tr>
 <th>ID</th>
 <th>Title</th>
 <th>Transaction Date</th>
 <th>Amount</th>
 </tr>
 <% @expenses.each do |expense| %>
 	<tr>
 	 <td> <%= expense.id %> </td>
 	 <td> <%= expense.title %> </td>
 	 <td> <%= expense.transaction_date %> </td>
 	 <td> <%=number_to_currency  expense.amount %> </td>
 	 </tr>
 	<% end %>
 	</table> 

app/views/expenses/new.html.erb
<%- model_class = Expense -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/expenses/show.html.erb
<%- model_class = Expense -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dt><strong><%= model_class.human_attribute_name(:transaction_date) %>:</strong></dt>
  <dd><%= @expense.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @expense.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @expense.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              expenses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_expense_path(@expense), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              expense_path(@expense),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width = device-width, initial-scale = 1"
scale = 1">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<html>
<head>
  <title>Expenses</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<nav>
			<% if user_signed_in? %>
			<%= image_tag current_user.gravatar_url %>
			<span>Hello <%= current_user.email %> </span>
			<%= link_to 'sign out',destroy_user_session_path, class: "btn btn-primary", method: :delete %>
			<%= link_to 'new expense',new_expense_path, class: "btn btn-primary" %>
			<%= link_to 'new open_house', new_open_house_path, class: "btn btn-primary" %>
			<%= link_to 'Expenses', expenses_path, class: "btn btn-primary" %>
			<%= link_to 'Open Houses', open_houses_path, class: "btn btn-primary" %>
     <% else %>
		
			<%= link_to 'sign up', new_user_registration_path, class: "btn btn-primary" %>
			<%= link_to 'sign in', new_user_session_path, class: "btn btn-primary" %>
			
			<% end %>
		</nav>

<body>
	
	<div id="main-container" class="container>"
		<div class="row">
			
				<h3>One Agent App </h3>
			</div>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
<div class="col-xs-9"><%= yield %>
	<div class= "col-xs-3">
		<h2> Advertisements </h2>
		<table style="width:100%">
		<TABLE BORDER> <TR BGCOLOR="#99CCFF"> <TH>Accountant</TH> <TH>Mortgage_Company  </TH><TH>Painter  </TH><TH>  Contractor</TH><TH>  Lawyer</TH><TH> Property_Tax_Reduction</TH><TH>  Home_Depot</TH> </TR>

</div>
</div>
</div>
</body>
</html>

app/views/layouts/layouts.html.erb
<div class="container-narrow">
  <div class="masthead">
    <%= render 'layouts/user_header' %>
    <h3 class="muted"><%= link_to "SimpleDevise", root_path %></h3>
    <h5 class="muted">A demo of using SimpleDB with Devise</h5>
  </div>
  <hr />
  <%= yield %>
</div>

app/views/open_houses/_form.html.erb
<%= form_for @open_house, :html => { :class => "form-horizontal open_house" } do |f| %>

    <% if @open_house.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@open_house.errors.count, "error") %> prohibited this open_house from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @open_house.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Name, :class => 'form-control' %>
    </div>
    <%= error_span(@open_house[:Name]) %>
  </div>
  <div class="control-group">
    <%= f.label :Phone_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Phone_number, :class => 'form-control' %>
    </div>
    <%= error_span(@open_house[:Phone_number]) %>
  </div>
  <div class="control-group">
    <%= f.label :Email_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Email_address, :class => 'form-control' %>
    </div>
    <%= error_span(@open_house[:Email_address]) %>
  </div>
  <div class="control-group">
    <%= f.label :How_did_you_here_about_our_open_house, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :How_did_you_here_about_our_open_house, :class => 'form-control' %>
    </div>
    <%= error_span(@open_house[:How_did_you_here_about_our_open_house]) %>
  </div>
  <div class="control-group">
    <%= f.label :Are_you_working_with_a_Realtor, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Are_you_working_with_a_Realtor, :class => 'form-control' %>
    </div>
    <%= error_span(@open_house[:Are_you_working_with_a_Realtor]) %>
  </div>
  <div class="control-group">
    <%= f.label :Realtors_name_and_contact_information, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Realtors_name_and_contact_information, :class => 'form-control' %>
    </div>
    <%= error_span(@open_house[:Realtors_name_and_contact_information]) %>
  </div>
  <div class="control-group">
    <%= f.label :Would_you_like_to_be_emailed_new_properties, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Would_you_like_to_be_emailed_new_properties, :class => 'form-control' %>
    </div>
    <%= error_span(@open_house[:Would_you_like_to_be_emailed_new_properties]) %>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%= error_span(@open_house[:user_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            open_houses_path, :class => 'btn btn-default' %>

<% end %>

app/views/open_houses/edit.html.erb
<%- model_class = OpenHouse -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/open_houses/index.html.erb
<%- model_class = OpenHouse -%>
<%= form_tag "/" , method: :get do %>
<%= text_field_tag :q, params[:q] %>
<%= submit_tag "Search" %>
<% end%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Name) %></th>
      <th><%= model_class.human_attribute_name(:Phone_number) %></th>
      <th><%= model_class.human_attribute_name(:Email_address) %></th>
      <th><%= model_class.human_attribute_name(:How_did_you_here_about_our_open_house) %></th>
      <th><%= model_class.human_attribute_name(:Are_you_working_with_a_Realtor) %></th>
      <th><%= model_class.human_attribute_name(:Realtors_name_and_contact_information) %></th>
      <th><%= model_class.human_attribute_name(:Would_you_like_to_be_emailed_new_properties) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @open_houses.each do |open_house| %>
      <tr>
        <td><%= link_to open_house.id, open_house_path(open_house) %></td>
        <td><%= open_house.Name %></td>
        <td><%= open_house.Phone_number %></td>
        <td><%= open_house.Email_address %></td>
        <td><%= open_house.How_did_you_here_about_our_open_house %></td>
        <td><%= open_house.Are_you_working_with_a_Realtor %></td>
        <td><%= open_house.Realtors_name_and_contact_information %></td>
        <td><%= open_house.Would_you_like_to_be_emailed_new_properties %></td>
        <td><%= open_house.user_id %></td>
        <td><%=l open_house.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_open_house_path(open_house), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      open_house_path(open_house),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_open_house_path,
            :class => 'btn btn-primary' %>

app/views/open_houses/new.html.erb
<%- model_class = OpenHouse -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/open_houses/show.html.erb
<%- model_class = OpenHouse -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Name) %>:</strong></dt>
  <dd><%= @open_house.Name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Phone_number) %>:</strong></dt>
  <dd><%= @open_house.Phone_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Email_address) %>:</strong></dt>
  <dd><%= @open_house.Email_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:How_did_you_here_about_our_open_house) %>:</strong></dt>
  <dd><%= @open_house.How_did_you_here_about_our_open_house %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Are_you_working_with_a_Realtor) %>:</strong></dt>
  <dd><%= @open_house.Are_you_working_with_a_Realtor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Realtors_name_and_contact_information) %>:</strong></dt>
  <dd><%= @open_house.Realtors_name_and_contact_information %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Would_you_like_to_be_emailed_new_properties) %>:</strong></dt>
  <dd><%= @open_house.Would_you_like_to_be_emailed_new_properties %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @open_house.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              open_houses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_open_house_path(@open_house), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              open_house_path(@open_house),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/site/index.html.erb
<div class="jumbotron">
  <img src="images/frontofhouse.jpg">
  <% if user_signed_in? %>
    <h1>Welcome back, trusted user!</h1>
    <p class="lead">
      You have signed in!  Welcome to On Agent App, track your expense and track your
      open house activity.
    </p>
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => 'btn btn-large btn-danger' %>
  <% else %>
    <h1>Welcome, new user!</h1>
    <p class="lead">
      You must sign in or sign up before you can access our super sweet,
      One Agent App .
    </p>
    <div class="row-fluid">
      <div class="span6">
        <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
      </div>
      <div class="span6">
        <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>